name: Deploy Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run tests (if available)
        working-directory: ./backend
        run: npm test --if-present

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: backend
          procfile: "web: node server.js"
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/api/health"
          rollbackonhealthcheckfailed: true

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Backend API is available at: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/api"
